### ISSUE TITLE
not showing files.

### ISSUE THREAD

**Issue by sharmauttam16** [guillermomartinez/filemanager-php#2]
continue showing progress status and not fetching files. 
did i miss something like url settings?

i did follow the exact steps you provided.

Thanks for this awesome script. 
![image](https://cloud.githubusercontent.com/assets/24384121/20882831/e08c7b16-bb08-11e6-9940-e84419ca8c95.png)

**Comment by guillermomartinez** [comment]
Prove that all files load well

![debug](https://cloud.githubusercontent.com/assets/5642429/20887553/162c144c-bac9-11e6-914c-e54c057f15ee.PNG)

**Comment by sharmauttam16** [comment]
here is my all directory structure and code of connector.php and index.html 
![screnn](https://cloud.githubusercontent.com/assets/24384121/20913924/a331dc9a-bba1-11e6-9b6a-67b06742d403.png)
![save](https://cloud.githubusercontent.com/assets/24384121/20913988/1cd808da-bba2-11e6-833f-0973697c701c.png)

what steps taken during installation : 
step 1. clone this script (Filemanager-ui) in htdocs using git command line.
step 2. install bower components.
step 3. create file index.html.
step 4. create conector.php file and set url to index.html file.
step 5. get filemanager php class from filemanager-php.
step 6. copy filemanager folder into script directory (you can see it in screenshot )
step 7. Create userfiles folder in filemanager folder. also try with create this folder in script directory .

thanks for your quick response :+1:

**Comment by mahesh986** [comment]
i have a same issue . please provide further guidance for installing this great script . :)

**Comment by guillermomartinez** [comment]
Check [Installation](https://github.com/guillermomartinez/filemanager-ui/wiki/Installation)
