### ISSUE TITLE
How to change upload max file size? 

### ISSUE THREAD

**Issue by admont28** [guillermomartinez/filemanager-php#4]
I am using filemanager-php with Laravel 5.4 integration, I need change upload max file size parameter, because when I load 10 images with 1 MB each one the filemanager says: 

> Máximo permitido: 5 MB.

How do I change this?

Thank you very much.

**Comment by guillermomartinez** [comment]
The message was incorrect, the correct message is: maximum allowed files 5  https://github.com/guillermomartinez/filemanager-php/commit/5a637f38e73fca58e4829ea48c1eb3ad30f5c331
Change the maximum number of files
```
$extra = array(
"upload" => array("number"=>10)
);
$f = new Filemanager($extra);
$f->run();
```
