### ISSUE TITLE
Soporte para Laravel 5.6

### ISSUE THREAD

**Issue by admont28** [guillermomartinez/filemanager-php#7]
Hola, Estoy actualizando la versión de Laravel 5.5 a Laravel 5.6 y composer me dice lo siguiente:

`laravel/framework v5.6.0 requires symfony/finder ~4.0`

y según [filemanager-php en Packagist.org](https://packagist.org/packages/guillermomartinez/filemanager-php)

`filemanager-php requires symfony/finder: ~2.5|3.*`

¿Se podría adicionar el soporte para laravel 5.6?

**Comment by guillermomartinez** [comment]
Ya se ha agregado soporte para Laravel 5.6
`composer update`

**Comment by admont28** [comment]
Agradezco mucho su colaboración.

Saludos.
